from pydantic import BaseModel, Field

from sandbox_game.etc.enums import CustomLlmProviderType


class CustomLlmProviderCreate(BaseModel):
    name: str = Field(
        ...,
        description='The name of the custom LLM provider.',
    )
    provider: CustomLlmProviderType = Field(
        ...,
        description='The type of the custom LLM provider.',
    )
    url: str = Field(
        ...,
        description='The base URL of the custom LLM provider.',
    )


class CustomLlmProvider(BaseModel):
    provider_id: int = Field(
        ...,
        description='The unique identifier for the custom LLM provider, generated by the database.',
    )
    name: str = Field(
        ...,
        description='The name of the custom LLM provider.',
    )
    provider: CustomLlmProviderType = Field(
        ...,
        description='The type of the custom LLM provider.',
    )
    url: str = Field(
        ...,
        description='The base URL of the custom LLM provider.',
    )
