from typing import Optional
from pydantic import BaseModel, Field

from sandbox_game.etc.enums import UserRole


class UserCreate(BaseModel):
    """
    A DTO for creating a new user.
    """

    username: str = Field(
        ...,
        description='The username of the user, used for login and display purposes. Must be unique.',
    )
    password: str = Field(
        ...,
        description='The password of the user in plain text. Will be hashed before being stored in the database.',
    )


class User(BaseModel):
    """
    A user in the system.
    """

    user_id: int = Field(
        ...,
        description='The unique identifier for the user, generated by the database.',
    )
    username: str = Field(
        ...,
        description='The username of the user, used for login and display purposes. Must be unique.',
    )
    password_hash: Optional[str] = Field(
        None,
        description='The hashed password of the user.',
    )

    role: UserRole = Field(
        ...,
        description='The role of the user.',
    )
